ci:
    autofix_commit_msg: |
        ci: auto fixes from pre-commit hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_commit_msg: 'ci: pre-commit autoupdate'
    autoupdate_schedule: monthly

default_language_version:
  python: python3.12

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
    exclude: ^examples/wrongjson\.json$
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: end-of-file-fixer
    exclude: ^(docs/flamegraphs/|rust/fuzz/corpus/|docs/conf\.py$|docs/requirements\.in$|examples/(bigexample|wrongjson)\.json$|lat\.md/lat\.md$|setup\.py$)
  - id: trailing-whitespace
    exclude: ^(CONTRIBUTING\.rst$|README\.rst$|benchmarks/benchmark\.sh$|examples/wrongjson\.json$|rust/fuzz/fuzz_targets/)
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.4
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/rstcheck/rstcheck
  rev: v6.2.4
  hooks:
  - id: rstcheck
    args:
    - --ignore-directives=highlight,toctree,automodule
    - --ignore-roles=ref
    exclude: ^(README|docs/readme)\.rst$
    additional_dependencies:
    - tomli==2.0.1
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
